#!/bin/bash -x

openssl req -new -x509 -days 9999 -nodes -newkey rsa:2048 \
    -out server_cert.pem -keyout server_key.pem \
    -subj "/C=US/ST=MO/L=St. Louis/O=OCI/CN=server"

cat server_cert.pem >>server_key.pem
cat server_cert.pem >cacert.pem

openssl req -new -x509 -days 9999 -nodes -newkey rsa:2048 \
    -out client_cert.pem -keyout client_key.pem \
    -subj "/C=US/ST=MO/L=St. Louis/O=OCI/CN=client"

cat client_cert.pem >>client_key.pem
cat client_cert.pem >>cacert.pem

